module.exports = {
    "en-IN": {
        "WELCOME_MESSAGE":"Welcome to Football Masters. Football is played with the head. Your feet are just the tools. So let's get started. I am going to ask you a question and you have to answer just by saying either of a, b, c or d. You will get 2 chances to score as much as possible. ",
        "QUESTION": "Are you ready for today's quiz?",
        "RETURNING_USERS_WELCOME": "Welcome back to Football Masters. ",
        "USEDQ": [],
        "QUESTIONS": [
        "Which player scored the fastest hat-trick in the Premier league? A.Ronaldo. B.Aguero. C.Mane. D.Salah.",
        "Which country won the first ever World Cup in 1930? A.Germany. B.Brazil. C.Argentina. D.Uruguay.",
        "Messi famously retired from international duty in which year before reversing his decision? A.2016. B.2014. C.2015. D.2017.",
        "Which Spanish club's nickname is Los Colchoneros, which translates to English as 'The Mattress Makers'? A.Atletico Madrid. B.Sevilla. C.Valencia. D.FC Barcelona.",
        "Who is the only player to win the Champions League with three different clubs? A.Ronaldinho. B.Ibrahimovic. C.Clarence Seedorf. D.David Beckham.",
        "Which outfield player appeared in the Champions League final in three different decades? A.Lionel Messi. B.Gigi Buffon. C.Zinedine Zidane. D.Ryan Giggs.",
        "Which player is England's all-time leading European Championship goal scorer and has a tally of seven goals? A.Wayne Rooney. B.Alan Shearer. C.Jimmy Greaves. D.Ashley cole.",
        "Which one of the following has not won the European Championship? A.Denmark. B.Belgium. C.Greece.",
        "Which manager first named David Beckham as the England captain? A.Pep Guardiola. B.Jose Mourinho. C.Peter Taylor. D.Alex Ferguson.",
        "Which club is associated with 'Galacticos'? A.Real Madrid. B.FC Barcelona. C.Chelsea. D. P S G .",
        "Which MLS franchise team does David Beckham own? A.LA Galaxy. B.Toronto FC. C.FC Dallas. D.Inter Miami CF.",
        "Which club is sometimes referred to as FC Hollywood? A.Inter Milan. B.AC Milan. C.Bayern Munich. D.Inter Miami.",
        "Which team won the first Premier League title? A.Chelsea. B.Manchester United. C.Manchester City. D.Liverpool.",
        "Who has scored the most number of goals in World Cup history? A.Cristiano Ronaldo. B.Miroslav Klose. C.Clarence Seedorf. D.Michael Owen.",
        "Which player has won the most number of Champions League trophies? A.Francisco Gento. B.Gerd Muller. C.Lionel Messi. D.Cristiano Ronaldo.",
        "Which country won the Football world Cup maximum times? A.Germany. B.Italy. C.Argentina. D.Brazil.",
        "Who among the following achieved the first World Cup hat-trick? A.Johino. B.Lucien Laurent. C.Bert Patenaude. D.Pele.",
        "Who was the last Manchester United player to win the Ballon d'Or before Cristiano Ronaldo? A.George Best. B.Ryan Giggs. C.Wayne Rooney. D.Steven Gerrad.",
        "Who scored the first perfect hattrick in the Premier League? A.Alan Shearer. B.Cristiano Ronaldo. C.Jimmy Floyd Hasselbaink. D.Wayne Rooney.",
        "Which player holds the record for most consecutive Premier League appearances? A.Brad Friedel. B.Bertrand. C.Ryan Giggs. D.Alan Shearer.",
        "Who is the world's most expensive teenager? A.Kylian Mbappe. B.Alphonse Davies C.Ansu Fati. D.Neymar.",
        "Which team saw themselves eliminated from the 2018 World Cup due to fair play rules? A.Portugal. B.Argentina. C.Senegal. D.Uruguay.",
        "Which Dutch player was voted European Player of the Century in 1999? A.Johan Cruyff. B.Van Basten. C.Denis Bergkamp. D.Ronald Koeman.",
        "Wayne Rooney scored his first Premier League goal against which team? A.Arsenal. B.Stoke City. C.Manchester City. D.Wolves.",
        "Which club won the 2017 UEFA Super Cup? A.Fc Barcelona. B.Sevilla. C.Atletico Madrid. D.Real Madrid.",
        "Which English Premier league side are known as The Red Devils?  A.Manchester United. B.Arsenal. C.Manchester City. D.Chelsea.",
        "How many times have Brazil won the World Cup? A 0. B 5. C 3. D 2.",
        "Which team are nicknamed The Canaries? A.Celtic. B.Liverpool. C.Norwich City. D.Brighton and Hove Albion.",
        "How many teams play in the FIFA World Cup? A. 32. B 16. C 12. D 28.",
        "Which football star is on the cover of the FIFA 20 game? A.Wayne Rooney. B.Cristiano Ronaldo. C.Eden Hazard. D.Lionel Messi.",

        ],
        
        "ANSWERS": [
        "c",
        "d",
        "a",
        "a",
        "c",
        "d",
        "b",
        "b",
        "c",
        "a",
        "d",
        "c",
        "b",
        "b",
        "a",
        "d",
        "c",
        "a",
        "c",
        "a",
        "a",
        "c",
        "a",
        "b",
        "d",
        "a",
        "b",
        "c",
        "a",
        "c",
        ],
    }
}